name: Optimized CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-deps.outputs.cache-hit }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          ~/.cache
        key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
        
    - name: Install dependencies
      run: npm install

  test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Restore dependencies from cache
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          ~/.cache
        key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
        
    - name: Run tests
      run: npm test 

  build:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Restore dependencies from cache
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          ~/.cache
        key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
        
    - name: Build project
      run: npm run build
      
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
